version: "3.2"
services:
  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan serve --host=0.0.0.0"
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - .:/app
    ports:
      - 8001:8000
    depends_on:
      - mysql_host
    networks:
      - mysql-phpmyadmin

  # user_service_queue:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: "php artisan queue:work"
  #   depends_on:
  #     - mysql_host

  mysql_host:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: ngml
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33061:3306
    networks:
      - processflow_network
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql_host
    image: phpmyadmin
    ports:
      - "8010:80"
    environment:
      PMA_HOST: mysql_host
      MYSQL_ROOT_PASSWORD: root
    networks:
      - processflow_network
    restart: unless-stopped
    volumes:
      - ./:/app

networks:
  processflow_network:
