version: "3.2"
services:
  processflow:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan serve --host=0.0.0.0"
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - .:/app
    ports:
      - 1010:8000
    networks:
      - processflow_network

  processflow_queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan queue:work"
    networks:
      - processflow_network

  mysql:
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD=forge
      - MYSQL_DATABASE=processflow
      - MYSQL_USER=forge
      - MYSQL_PASSWORD=forge
    networks:
      - processflow_network
  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "1011:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PASSWORD=forge
    networks:
      - processflow_network
    restart: unless-stopped
    volumes:
      - ./:/app

networks:
  processflow_network:
